name: Testing CI

on:
  push:
    branches: [ master, vendoring-experiment ]
  pull_request:
    branches: [ master ]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Virtualenvs
      uses: actions/cache@v1
      with:
        path: ~/miniconda3
        key: ${{ runner.OS }}-env-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'makefile*') }}

    - name: make conda
      run: make conda

    - name: make lint
      run: make lint

    - name: make mypy
      run: make mypy

    - name: make test
      run: make test

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Virtualenvs
      uses: actions/cache@v1
      with:
        path: ~/miniconda3
        key: ${{ runner.OS }}-env-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'makefile*') }}

    - name: make conda
      run: make conda

    - name: make lint
      run: make lint || true

    - name: make mypy
      run: make mypy

    - name: make test
      run: make test
